//下拉菜单的数据(handleNvbcontent):
var aNvbContentData =[
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1719"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1729"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1739"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米CC9",
			price:"1709"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji3.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji3.jpg",
			name:"小米CC9",
			price:"1719"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1709"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米CC9",
			price:"1719"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji3.jpg",
			name:"小米CC9",
			price:"1729"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1739"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米CC9",
			price:"1719"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1729"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1739"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1709"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji3.jpg",
			name:"小米CC9",
			price:"1719"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji3.jpg",
			name:"小米CC9",
			price:"1729"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji3.jpg",
			name:"小米CC9",
			price:"1739"
		},
	],
]

//分类列表数据(handleCate)
var aCateContentData =[
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-4"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-5"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-6"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米手机2-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米手机2-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-4"
		},
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米手机3-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji2.jpg",
			name:"小米手机3-2"
		},
	],
]